language: python
sudo: required
dist: bionic
os: linux
services:
  - docker
python:
  - "3.7"
  - "3.11"
  - pypy3

install:
  - pip install "python-dateutil==2.8.2"
  - pip install -e .[ci]
  - pip install coveralls
before_script:
  - docker-compose up -d
script:
  - inv cover qa
after_success:
  - coveralls --rcfile=coverage.rc

matrix:
  allow_failures:
    - python: pypy3
