language: python
sudo: required
dist: jammy
os: linux
services:
  - docker
python:
  - "3.8"
  - "3.11"
  - "pypy3"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install .[ci]
  - pip install coveralls
before_script:
  - docker-compose up -d
script:
  - inv cover qa
after_success:
  - coveralls --rcfile=coverage.rc

matrix:
  allow_failures:
    - python: pypy3
