---
name: Flask-FS2 CI

on: [push, pull_request]

jobs:
  ci:
    name: Test with different versions of Python 🐍
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: pip
      - name: Upgrade pip 📦
        run: >-
          python -m pip install --upgrade pip setuptools
      - name: Install packages 📦
        run: >-
          python -m pip install .[ci]
      - name: Install flask-mongoengine and pytest-flask from git 📦
        run: >-
          python -m pip install
          "flask-mongoengine @ git+https://github.com/idoshr/flask-mongoengine.git@json_encoder"
          "pytest-flask @git+https://github.com/threeal/pytest-flask.git@remove-request-ctx"
      - name: Launch dockers 🐳
        run: >-
          docker-compose up -d
      - name: Run tests 🧪
        run: >-
          inv cover qa
      - name: Show coverage report 📊
        run: >-
          coveralls --rcfile=coverage.rc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
